# This is a basic workflow to help you get started with Actions

name: Open Issue Tracker
on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  issue_tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Content
        run: |
          echo "New Issue Content:"
          echo "Title: ${{ github.event.issue.title }}"
          echo "Body: ${{ github.event.issue.body }}"
